version: '3.8'

name: ang-go-crud

networks:
  ang-go-crud-network:
    driver: bridge

services:

  db:
    image: postgres
    hostname: localhost
    networks:
      - ang-go-crud-network
    ports:
      - "5432:5432"
    env_file:
      - .db.dev.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.server.dev
    env_file:
      - .server.dev.env
    networks:
      - ang-go-crud-network
    volumes:
      - ./server:/app/
      - /app/tmp
    ports: 
      - '1323:1323'

  client:
    depends_on:
      - server
    build:
      dockerfile: Dockerfile.client.dev
    networks:
      - ang-go-crud-network
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    ports:
      - '4200:4200'

volumes:
  pgdata: